# See https://github.com/golangci/golangci-lint/blob/master/.golangci.example.yml
run:
  tests: true

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
  gocyclo:
    min-complexity: 20
  dupl:
    threshold: 100
  misspell:
    locale: US
  unused:
    check-exported: false
  unparam:
    check-exported: true
  cyclop:
    max-complexity: 18
  funlen:
    lines: 120
    statements: 60
  nestif:
    min-complexity: 6

linters:
  enable-all: true
  disable:
    - gochecknoinits
    - scopelint
    - exhaustive
    - lll
    - maligned
    - gochecknoglobals
    - gomnd
    - wrapcheck
    - paralleltest
    - forbidigo
    - exhaustivestruct
    - interfacer # deprecated
    - forcetypeassert
    - scopelint # deprecated
    - ifshort # too many false positives

issues:
  exclude-use-default: false
  exclude-rules:
    - linters:
        - gomnd
        - goconst
        - goerr113
        - noctx
        - funlen
        - dupl
        - errcheck
        - errorlint
      path: "_test.go"

