# This script is provided by github.com/bool64/dev.
name: gorelease
on:
  pull_request:
env:
  GO111MODULE: "on"
jobs:
  gorelease:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go stable
        if: matrix.go-version != 'tip'
        uses: actions/setup-go@master
        with:
          go-version: 1.17.x
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Gorelease cache
        uses: actions/cache@v2
        with:
          path: |
            ~/go/bin/gorelease
          key: ${{ runner.os }}-gorelease-1.17
      - name: Gorelease
        id: gorelease
        run: |
          test -e ~/go/bin/gorelease || go install golang.org/x/exp/cmd/gorelease@latest
          OUTPUT=$(gorelease || exit 0)
          echo "${OUTPUT}"
          OUTPUT="${OUTPUT//$'\n'/%0A}"
          echo "::set-output name=report::$OUTPUT"
      - name: Comment Report
        continue-on-error: true
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: gorelease
          message: |
            ### Go API Changes

            <pre>
            ${{ steps.gorelease.outputs.report }}
            </pre>